### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by alexbilbie** [phprest/phprest#1]
Once you've set valid API versions how do you limit an endpoint to a specific version?

**Comment by adammbalogh** [comment]
Good question, I don't.

Should I?

I'm trying to make the framework layer as thin as possible, but it is kinda' hard. Maybe I do not want to give a general solution for this problem, maybe an individual service should solve this one.

Anyway, just to be on the same page, are you talking about e.g. a resource will be deprecated from version 2 and we want to tell this to the client?

**Comment by alexbilbie** [comment]
So the reason why you'd version an API is so you can add/remove/change methods.

Therefore unless you can limit endpoints to specific versions then the API versioning methods you've added are a bit redundant.

Perhaps a good way of doing this it to have an extra parameter on the routing which accepts an array of valid route endpoints, e.g.

``` php
$app->get('/foo', '1.0', function (Request $request) { /** do stuff for version 1.0 **/ });

$app->get('/foo', '2.0', function (Request $request) { /** do different stuff for version 2.0 **/ });
```

**Comment by alexbilbie** [comment]
Actually a better way of doing it might be to manipulate the incoming request with some middleware so that the version is added to the path. Then you can just do normal routing like so:

``` php
$app->get('/1.0/foo', function (Request $request) { /** do stuff for version 1.0 **/ });

$app->get('/2.0/foo', function (Request $request) { /** do different stuff for version 2.0 **/ });
```

If the version doesn't matter then you can use regex in the route:

``` php
$app->get('/{version:[0-9].[0-9]}/foo', function (Request $request) { /** do stuff for any version **/ });
```

**Comment by adammbalogh** [comment]
I see, thanks. Great idea. I've had a feeling that something is missing from the versioning part.

A middleware could be a correct place to implement this behaviour. And it can also handle the incorrect api versions.

**Comment by adammbalogh** [comment]
Would you like to contribute if you've time next year?

**Comment by alexbilbie** [comment]
I've created a working example here https://gist.github.com/alexbilbie/4d3e949dadfe34a65d74

**Comment by adammbalogh** [comment]
@alexbilbie opinion?

**Comment by alexbilbie** [comment]
Opinion on what sorry?

**Comment by adammbalogh** [comment]
About the implementation:

Main parts are:
- https://github.com/phprest/phprest#api-versioning
- https://github.com/phprest/phprest/blob/master/src/Middleware/ApiVersion.php
- https://github.com/phprest/phprest/blob/master/src/Annotation/Route.php
