### ISSUE TITLE
Is there a way to replace the error formatter ?

### ISSUE THREAD

**Issue by marcaube** [phprest/phprest#16]
I'm working on a project that has to adhere to the [JSON API](http://jsonapi.org/) response format, and one on the things prescribed in the spec is the [format and content of errors](http://jsonapi.org/format/#errors) (see [error examples](http://jsonapi.org/examples/#error-objects)).

As far as I can tell, there is no way to replace the error formatter with my own in order to format the errors properly.

**Comment by adammbalogh** [comment]
@marcaube I guess this question is not relevant, sorry. Anyway you could create your own error formatter (see [Formatter/JsonXml.php](https://github.com/phprest/phprest/blob/master/src/ErrorHandler/Formatter/JsonXml.php)) and after that you can set your own (see [how](https://github.com/phprest/phprest/blob/master/src/Config.php#L107)).

**Comment by marcaube** [comment]
So I should do something like this ?

``` php
$config = new Config('vendor.name', '0.1', true);
$config->getErrorHandler()->pushFormatter(new MyCustomFormatter($config));

$app = new Application($config);
```

**Comment by adammbalogh** [comment]
Yes, that should work!

**Comment by marcaube** [comment]
Alright, thanks!
