### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by adammbalogh** [phprest/phprest#2]
The current configuration is messy.

I don't want to be too strict, but I "have to" because I'd like to use some helper cli scripts:
- routes:get
- orm migrations
- orm fixtures

Now the scripts have concrete paths to their configurations. If this path does not exist then we turn to the `paths.php` file (which have to be in the root dir). This `paths.php` returns with an array with the actual config paths.

**We should find a better way to do this.**
(Or an improvement for this `paths.php` version)
Maybe environment variables, but I would not go that way.

**Comment by adammbalogh** [comment]
For the sake of simplicity for now I don't change the operation of the config.

**Comment by sagikazarmark** [comment]
Proton has something built-in called config, but I am not sure that's enough for you.

**Comment by adammbalogh** [comment]
Yes, I want explicit configuration which does not require extra documentation.
