### ISSUE TITLE
Annotations

### ISSUE THREAD

**Issue by adammbalogh** [phprest/phprest#3]
It might a good thing to create a mini section for annotation concepts in a Php manner. (?)

A lot of people hate annotations in Php because "those are just comments". @rdohms has the most awesome presentations in this subject. I'd like to put a reference to this prezi in the annotation section.

Should we do this or just leave annotation haters alone in the dark? :smiling_imp:

**Comment by willdurand** [comment]
The use of annotations is not mandatory I guess, so an alternative would be not to use annotations in the doc :)

**Comment by adammbalogh** [comment]
It is not mandatory, you're right.

Or an alternative would be put some file config examples in the doc.

**Comment by adammbalogh** [comment]
I've "solved" this with a simple advice: https://github.com/phprest/phprest/commit/0bb3496cfd23352f7c1006d34f0ef86c0ebec4e1
