### ISSUE TITLE
Problem with the ErrorHandlers

### ISSUE THREAD

**Issue by marcaube** [phprest/phprest#4]
In one of my endpoints, I validate a date param with the following code:

``` php
public function index(Request $request)
{
    if ($date = $request->query->get('date')) {
        try {
            $date = new \DateTime($date);
        } catch (\Exception $e) {
            throw new Exception\BadRequest();
        }
    }

    // ...
}
```

If I make a request to `/endpoint?date=foobar` I get the following response:

``` json
{"code":0,"message":"Bad Request","details":[]}{"code":0,"message":"DateTime::__construct(): Failed to parse time string (foobar) at position 0 (f): The timezone could not be found in the database","details":[]}
```

There's the `BadRequest` exception I thrown followed by the one I'm supposed to have caught.

Am I doing it wrong?

**Comment by adammbalogh** [comment]
What would you like to see as a response?

The response you see is generated by the default exception handler. You throw a `BadRequest` exception and phprest generates a default wrapped response.

**Comment by marcaube** [comment]
I only expected:

``` json
{"code":0,"message":"Bad Request","details":[]}
```

The api consumers don't need to know that I suck at parsing dates, and that's why I catch the exception and throw a generic one. When debug is `false`, these kind of error messages should not be returned to the users.

**Comment by adammbalogh** [comment]
I've just seen you get an invalid json response.

`{"code":0,"message":"Bad Request","details":[]}{"code":0,"message":"DateTime::__construct(): Failed to parse time string (foobar) at position 0 (f): The timezone could not be found in the database","details":[]}`

Have you got exactly this response?

And you're right when debug is `false` you should see that message. So there is a bug, I'll check it.

Do you use the sample project?

**Comment by marcaube** [comment]
Yeah I got exactly this response.

I do not use the sample project, but it's pretty close. I use fractal instead of the serializer and generate api docs with swagger-php ... but that's about it.

I can test with the sample project to see if the same issue exist.

**Comment by adammbalogh** [comment]
I have to update the `phprest\phprest` dependency in the sample project.

I am going to try to reproduce the error.

**Comment by marcaube** [comment]
I just installed the sample project and tweaked the `Camera->get()` method to reproduce my problem

``` php
/**
 * @Phprest\Route(method="GET", path="/camera")
 *
 * @Docs\Api(
 *      path="/camera",
 *      @Docs\Operation(
 *          method="GET", summary="Gets the camera",
 *          @Docs\Parameter(name="accept", required=false, type="string", paramType="header"),
 *          @Docs\Parameter(name="date", type="string", paramType="query"),
 *          @Docs\ResponseMessage(code=404, message="Not Found"),
 *          @Docs\ResponseMessage(code=200, message="Ok")
 *      )
 * )
 *
 * @param Request $request
 * @return Response\Ok
 * @throws Exception\BadRequest
 * @throws Exception\NotFound
 */
public function get(Request $request)
{
    if ($date = $request->query->get('date')) {
        try {
            $date = new \DateTime($date);
        } catch (\Exception $e) {
            throw new Exception\BadRequest();
        }
    }

    $repo = $this->serviceOrm()->getRepository('Api\Camera\Entity\Camera');

    if (is_null($camera = $repo->findOneBy([]))) {
        throw new Exception\NotFound();
    }

    return new Response\Ok($camera);
}
```

The response is still invalid JSON, but no mention of `DateTime`

``` json
{"code":0,"message":"Server Error","details":[]}{"code":0,"message":"Server Error","details":[]}
```

**Comment by marcaube** [comment]
It's the logger in the sample project that overwrites the `DateTime` error with `'Server Error'`. If I disable the logger, I've got the exact same Response than in my project.

**Comment by adammbalogh** [comment]
Could you test it please? It works for me now.

**Comment by marcaube** [comment]
I updated and it works. What's up with the `$config->setApiVersionHandler()`? It was removed?

**Comment by adammbalogh** [comment]
Yes it was. I've to find a better place for it.
