### ISSUE TITLE
Update Proton

### ISSUE THREAD

**Issue by sagikazarmark** [phprest/phprest#6]
Proton (and the underlying libraries) changed a lot in the near past. Orno DI and Route are moved to the League, the container now supports ServiceProviders (which you called Serviceable I think), Proton has a simple configuration interface.

I am happy to help in upgrading as this seems to be a good initiative.

**Comment by adammbalogh** [comment]
There is a plan for the update. In a couple of weeks (i hope) it will be done. Next week I am not available, after that I'll continue the development.

I'll ping you when the update task is actual.

**Comment by philipobenito** [comment]
You open to a PR on this if I get a chance this week some time?

**Comment by adammbalogh** [comment]
@philipobenito I'd like to finish the unit tests before the update. I am skiing this week. Next week we (w/ sagikazarmark) could talk about it through irc (?)

**Comment by sagikazarmark** [comment]
Yup. But I am not sure finishing unit tests prior to update makes sense. Why would you write things then change them?

Also, the service thing which currently exists in phprest would probably completely changed because of the Service Providers introduced in both League\Container and Proton.

**Comment by adammbalogh** [comment]
I think unit tests will help. Hopefully most things won't change. 

And I'd like to keep a linear project path at least for version 1.0

**Comment by adammbalogh** [comment]
I've created a branch for the update.

I don't want to bother neither the service providers nor the error handler (cause booboo in proton) yet.

I'll update/test the individual services and the sample app later this/next week.

**Comment by sagikazarmark** [comment]
BooBoo integration is WIP: alexbilbie/Proton#3

**Comment by adammbalogh** [comment]
Yap, I'm following that thread, looks nice.

I'll need an own json and xml formatter, but the prior issue is this one, so booboo will be only an enhancement.
