### ISSUE TITLE
Question: stable version, tags and releases

### ISSUE THREAD

**Issue by marcaube** [phprest/phprest#9]
Hi @adammbalogh,

we are thinking about using this project to build a new API, but the lack of a stable version (or at least tagged versions) could be a deal-breaker. I realize that all the dependencies used in the project _are_ stable, but being able to put a version contraint on `phprest/phprest` would make the choice easier for us.

What do you think of tagging a `0.1.0` release and adding a `1.0.x-dev` branch alias to the repository?

**Comment by adammbalogh** [comment]
Hello @marcaube,

Sorry for the very late response. Unfortunately I don't have any time these days, but next week I'll do it. I'll reach you some way.

**Comment by adammbalogh** [comment]
@marcaube I've created the tag and the branch as well.

**Comment by marcaube** [comment]
By branch alias, I meant a [composer branch alias](https://getcomposer.org/doc/articles/aliases.md#branch-alias). Thanks for the tag, we'll be able to lock our version constraint.

**Comment by adammbalogh** [comment]
Oh, I see. Thanks for the tip.

Should I put the branch alias into the tag as well?

**Comment by marcaube** [comment]
> Should I put the branch alias into the tag as well?

No, the tag is perfect as is. The alias is only to tell composer that the `dev-master` branch should be treated as `1.0@dev`. So executing `composer require phprest/phprest 1.0.*` would install `dev-master`.

If you plan to release more minor versions before stabilizing to `1.0`, you branch alias should be `0.2.x-dev` instead.

I hope it makes sense.

**Comment by adammbalogh** [comment]
Absolutely. Thank you.
